### ISSUE TITLE
About Jubeat LED

### ISSUE THREAD

**Issue by wayne1203** [Nadeflore/ACreal_IO#7]
Hi, thanks for the library.
I got some questions about using this for Jubeat
I'm using Mega 2560 and has been set to COM2
Is it using A8,A9,A10 pins?
Also, is it have any setting need to do after program uploaded to board?
Thank you

**Comment by Nadeflore** [comment]
Hi there,
Support for the 6th RGB LED, was added by @mickabrig7.
The current version on this repo does include support for it on jubeat. But @mickabrig7 made a pull request #6 , for jubeat support.
I'll merge it as soon as I'm able to confirm it runs well.

So right now if you want support for the 6th RGB led on jubeat, you can just grab his version : https://github.com/mickabrig7/ACreal_IO

**Comment by wayne1203** [comment]
That's great,
I tried @mickabrig7 version but not effect when I start Jubeat
So I'm thinking is it my setting getting wrong?
Thank for our help

**Comment by mickabrig7** [comment]
Did you properly set your gamemode and pinout in pinoutconfig.h ?
Are your RGB strips / LEDs wired correctly ? Don't forget that you can't power entire LED strips from an Arduino board, you need transistors to do so.
Also, please keep in mind that jubeat support is only for emulating a LEDboard and not an IOboard.

**Comment by Nadeflore** [comment]
You mean, everything is working fine, except the 6th rbg led ?
Or do you have any other issue to get it working ?

**Comment by wayne1203** [comment]
I set the GAMETYPE to 3 in pinoutconfig.h but I didn't set the pinout, is it just only using 6th (A8,A9,A10)
Also, I tested the led is work when I using example program in Arduino Sketch | Arduino Lesson 3. RGB LEDs 
Oh, I just trying to add RGB LED so I just got this issue only
Thank you for @Nadeflore and @mickabrig7 quick reply

**Comment by mickabrig7** [comment]
So, what exactly is working ? Every LEDs except the 6th one or none of them ?

**Comment by wayne1203** [comment]
I tried with 1. 7,6,5 | 2. 10,9,8 | 3. 13,12,11 | 4. 4,3,2 | 5. 46,45,44 | 6. A8,A9,A10 also not work.
I don't have card reader so I don't know how works with card reader.

**Comment by Nadeflore** [comment]
For the ledboard to work with jubeat, you do need a real reader

Closing this issue.
